backend:
  name: github
  repo: zoff-collective/bruderland

collections:
  - name: "chapter"
    label: "Chapter"
    folder: "data/chapter"
    create: true
    preview: false
    slug: "{{slug}}"
    fields:
      - label: "Titel"
        name: "title"
        widget: "string"
      - label: "Publikationsdatum"
        name: "publication-date"
        widget: "datetime"
      - label: "Bild"
        name: "featured-image"
        widget: "image"
      - label: "Inhalt"
        name: "content"
        widget: "markdown"
        buttons:
          - "bold"
          - "italic"
          - "link"
          - "heading-two"

media_folder: "static/media/uploads"
